# Peek at `Type1Diabetes.parquet`

Quick look at the schema and first rows using DuckDB. The file is ~1.3 GB / ~133M rows, so we query it in place instead of loading it all into pandas.

In [1]:
import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)

PARQUET = "../data/Type1Diabetes.parquet"
con = duckdb.connect()

## 1. Schema (`DESCRIBE`)

In [2]:
schema_df = con.sql(f"DESCRIBE SELECT * FROM '{PARQUET}'").df()
schema_df

                       column_name   column_type null   key default extra
0                              CGM        DOUBLE  YES  None    None  None
1                              age        DOUBLE  YES  None    None  None
2                         air_temp        DOUBLE  YES  None    None  None
3                            basal        DOUBLE  YES  None    None  None
4                            bolus        DOUBLE  YES  None    None  None
5                  calories_burned        DOUBLE  YES  None    None  None
6                            carbs        DOUBLE  YES  None    None  None
7                       cgm_device       VARCHAR  YES  None    None  None
8                       misc_notes       VARCHAR  YES  None    None  None
9                             date  TIMESTAMP_NS  YES  None    None  None
10          galvanic_skin_response        DOUBLE  YES  None    None  None
11                       heartrate        DOUBLE  YES  None    None  None
12                          height        DOUBLE  YES  None    None  None
13                              id       VARCHAR  YES  None    None  None
14                         insulin        DOUBLE  YES  None    None  None
15      insulin_delivery_algorithm       VARCHAR  YES  None    None  None
16         insulin_delivery_device       VARCHAR  YES  None    None  None
17       insulin_delivery_modality       VARCHAR  YES  None    None  None
18              insulin_type_basal       VARCHAR  YES  None    None  None
19              insulin_type_bolus       VARCHAR  YES  None    None  None
20                     is_pregnant       BOOLEAN  YES  None    None  None
21                         is_test       BOOLEAN  YES  None    None  None
22                      meal_label       VARCHAR  YES  None    None  None
23                       skin_temp        DOUBLE  YES  None    None  None
24                     source_file       VARCHAR  YES  None    None  None
25                           steps        DOUBLE  YES  None    None  None
26                          weight        DOUBLE  YES  None    None  None
27                workout_duration        DOUBLE  YES  None    None  None
28               workout_intensity        DOUBLE  YES  None    None  None
29                   workout_label       VARCHAR  YES  None    None  None
30                 treatment_group       VARCHAR  YES  None    None  None
31              randomization_date  TIMESTAMP_NS  YES  None    None  None
32                  extension_date  TIMESTAMP_NS  YES  None    None  None
33                          gender       VARCHAR  YES  None    None  None
34                age_of_diagnosis        DOUBLE  YES  None    None  None
35                       ethnicity       VARCHAR  YES  None    None  None
36  subject_split_across_traintest       BOOLEAN  YES  None    None  None

## 2. All column names

In [3]:
columns = schema_df["column_name"].tolist()
print(f"{len(columns)} columns:")
for name, dtype in zip(schema_df["column_name"], schema_df["column_type"]):
    print(f"  {name:<32} {dtype}")

37 columns:
  CGM                              DOUBLE
  age                              DOUBLE
  air_temp                         DOUBLE
  basal                            DOUBLE
  bolus                            DOUBLE
  calories_burned                  DOUBLE
  carbs                            DOUBLE
  cgm_device                       VARCHAR
  misc_notes                       VARCHAR
  date                             TIMESTAMP_NS
  galvanic_skin_response           DOUBLE
  heartrate                        DOUBLE
  height                           DOUBLE
  id                               VARCHAR
  insulin                          DOUBLE
  insulin_delivery_algorithm       VARCHAR
  insulin_delivery_device          VARCHAR
  insulin_delivery_modality        VARCHAR
  insulin_type_basal               VARCHAR
  insulin_type_bolus               VARCHAR
  is_pregnant                      BOOLEAN
  is_test                          BOOLEAN
  meal_label                       VARCHAR
  skin_temp                        DOUBLE
  source_file                      VARCHAR
  steps                            DOUBLE
  weight                           DOUBLE
  workout_duration                 DOUBLE
  workout_intensity                DOUBLE
  workout_label                    VARCHAR
  treatment_group                  VARCHAR
  randomization_date               TIMESTAMP_NS
  extension_date                   TIMESTAMP_NS
  gender                           VARCHAR
  age_of_diagnosis                 DOUBLE
  ethnicity                        VARCHAR
  subject_split_across_traintest   BOOLEAN

## 3. First 5 rows

In [4]:
head_df = con.sql(f"SELECT * FROM '{PARQUET}' LIMIT 5").df()
head_df

,CGM,age,air_temp,basal,bolus,calories_burned,carbs,cgm_device,misc_notes,date,galvanic_skin_response,heartrate,height,id,insulin,insulin_delivery_algorithm,insulin_delivery_device,insulin_delivery_modality,insulin_type_basal,insulin_type_bolus,is_pregnant,is_test,meal_label,skin_temp,source_file,steps,weight,workout_duration,workout_intensity,workout_label,treatment_group,randomization_date,extension_date,gender,age_of_diagnosis,ethnicity,subject_split_across_traintest
0,NaN,NaN,NaN,0.05,NaN,NaN,NaN,Medtronic Enlite,None,2027-04-07 09:20:00,NaN,NaN,NaN,596,0.05,None,MiniMed 530G,SAP,humalog,humalog,<NA>,False,None,NaN,OhioT1DM,NaN,NaN,NaN,NaN,None,None,NaT,NaT,Male,NaN,None,False
1,NaN,NaN,NaN,0.05,NaN,NaN,NaN,Medtronic Enlite,None,2027-04-07 09:25:00,NaN,NaN,NaN,596,0.05,None,MiniMed 530G,SAP,humalog,humalog,<NA>,False,None,NaN,OhioT1DM,NaN,NaN,NaN,NaN,None,None,NaT,NaT,Male,NaN,None,False
2,NaN,NaN,NaN,0.05,NaN,NaN,NaN,Medtronic Enlite,None,2027-04-07 09:30:00,NaN,NaN,NaN,596,0.05,None,MiniMed 530G,SAP,humalog,humalog,<NA>,False,None,NaN,OhioT1DM,NaN,NaN,NaN,NaN,None,None,NaT,NaT,Male,NaN,None,False
3,NaN,NaN,NaN,0.05,NaN,NaN,NaN,Medtronic Enlite,None,2027-04-07 09:35:00,NaN,NaN,NaN,596,0.05,None,MiniMed 530G,SAP,humalog,humalog,<NA>,False,None,NaN,OhioT1DM,NaN,NaN,NaN,NaN,None,None,NaT,NaT,Male,NaN,None,False
4,NaN,NaN,NaN,0.05,NaN,NaN,NaN,Medtronic Enlite,None,2027-04-07 09:40:00,NaN,NaN,NaN,596,0.05,None,MiniMed 530G,SAP,humalog,humalog,<NA>,False,None,NaN,OhioT1DM,NaN,NaN,NaN,NaN,None,None,NaT,NaT,Male,NaN,None,False

Transposed view (easier to read with 37 columns):

In [5]:
head_df.T

                                                  0                    1                    2                    3                    4
CGM                                             NaN                  NaN                  NaN                  NaN                  NaN
age                                             NaN                  NaN                  NaN                  NaN                  NaN
air_temp                                        NaN                  NaN                  NaN                  NaN                  NaN
basal                                          0.05                 0.05                 0.05                 0.05                 0.05
bolus                                           NaN                  NaN                  NaN                  NaN                  NaN
calories_burned                                 NaN                  NaN                  NaN                  NaN                  NaN
carbs                                           NaN                  NaN                  NaN                  NaN                  NaN
cgm_device                         Medtronic Enlite     Medtronic Enlite     Medtronic Enlite     Medtronic Enlite     Medtronic Enlite
misc_notes                                     None                 None                 None                 None                 None
date                            2027-04-07 09:20:00  2027-04-07 09:25:00  2027-04-07 09:30:00  2027-04-07 09:35:00  2027-04-07 09:40:00
galvanic_skin_response                          NaN                  NaN                  NaN                  NaN                  NaN
heartrate                                       NaN                  NaN                  NaN                  NaN                  NaN
height                                          NaN                  NaN                  NaN                  NaN                  NaN
id                                              596                  596                  596                  596                  596
insulin                                        0.05                 0.05                 0.05                 0.05                 0.05
insulin_delivery_algorithm                     None                 None                 None                 None                 None
insulin_delivery_device                MiniMed 530G         MiniMed 530G         MiniMed 530G         MiniMed 530G         MiniMed 530G
insulin_delivery_modality                       SAP                  SAP                  SAP                  SAP                  SAP
insulin_type_basal                          humalog              humalog              humalog              humalog              humalog
insulin_type_bolus                          humalog              humalog              humalog              humalog              humalog
is_pregnant                                    <NA>                 <NA>                 <NA>                 <NA>                 <NA>
is_test                                       False                False                False                False                False
meal_label                                     None                 None                 None                 None                 None
skin_temp                                       NaN                  NaN                  NaN                  NaN                  NaN
source_file                                OhioT1DM             OhioT1DM             OhioT1DM             OhioT1DM             OhioT1DM
steps                                           NaN                  NaN                  NaN                  NaN                  NaN
weight                                          NaN                  NaN                  NaN                  NaN                  NaN
workout_duration                                NaN                  NaN                  NaN                  NaN                  NaN
workout_intensity                               NaN                  NaN                  NaN                  NaN                  NaN
workout_label                                  None                 None                 None                 None                 None
treatment_group                                None                 None                 None                 None                 None
randomization_date                              NaT                  NaT                  NaT                  NaT                  NaT
extension_date                                  NaT                  NaT                  NaT                  NaT                  NaT
gender                                         Male                 Male                 Male                 Male                 Male
age_of_diagnosis                                NaN                  NaN                  NaN                  NaN                  NaN
ethnicity                                      None                 None                 None                 None                 None
subject_split_across_traintest                False                False                False                False                False